spring:
  application:
    name: "configserver"
  profiles:
    #active: "native"
    active: "git"
  cloud:
    config:
      server:
        #native:
          #searchLocations: "classpath:/config"
          #searchLocations: "file:///D:/JAVA/UDemy/Microservices/documents/config"
        git:
          uri: "https://github.com/surajya/esaybyte-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  key: "SDASJK331J213K12J323K21K213J232KL12K2KJ323KJ123K"

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

server:
    port: 8071

    #For webhook, 1. hookdeck listen 8071 --path /monitor   #2. if source is not present create localhost source
